### ISSUE TITLE
Could not find a parent AdapterView

### ISSUE THREAD

**Issue by birijan** [balysv/material-ripple#45]
I'm frequently getting exception below while using material-ripple,  usually while resuming the app. Can you please check it out and let me know how to ignore such exception. 

Thanks in advance.

E/AndroidRuntime(29863): java.lang.RuntimeException: Could not find a parent AdapterView
E/AndroidRuntime(29863): 	at com.balysv.materialripple.MaterialRippleLayout.findParentAdapterView(MaterialRippleLayout.java:409)
E/AndroidRuntime(29863): 	at com.balysv.materialripple.MaterialRippleLayout.adapterPositionChanged(MaterialRippleLayout.java:423)
E/AndroidRuntime(29863): 	at com.balysv.materialripple.MaterialRippleLayout.draw(MaterialRippleLayout.java:474)
E/AndroidRuntime(29863): 	at android.view.View.updateDisplayListIfDirty(View.java:14167)

**Comment by balysv** [comment]
If using `app:mrl_rippleInAdapter="true"            // if true, MaterialRippleLayout will optimize for use in AdapterViews`, there must be an `AdapterView` in the parent hierarchy of `MaterialRippleLayout`, otherwise this exception is thrown.

Set `app:mrl_rippleInAdapter="false"` or check your view hierarchy. Note that `RecyclerView` is not an `AdapterView`

**Comment by chi5hao** [comment]
oh no~ recyclerview can't work...

**Comment by chi5hao** [comment]
is there any solution for recycleView?

**Comment by CreaRo** [comment]
This exception is thrown when the MRL exists inside the XML of an included element. That shouldnt happen.
