### ISSUE TITLE
Null pointer exception on scrolling listview

### ISSUE THREAD

**Issue by aebmgroup** [balysv/material-ripple#52]
When you click on ripple view and then scroll it fast enough to exit from listview layout (while ripple animation is already running) it threw a null pointer exception for onclick listener.

**Comment by ngheungyu** [comment]
Similar crash when mri_rippleInAdapter is true, it happens sometimes in HTC One_M8

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
       at android.widget.AdapterView.getPositionForView(AdapterView.java:602)
       at com.balysv.materialripple.MaterialRippleLayout$PerformClickEvent.clickAdapterView(MaterialRippleLayout.java:653)
       at com.balysv.materialripple.MaterialRippleLayout$PerformClickEvent.run(MaterialRippleLayout.java:645)
       at com.balysv.materialripple.MaterialRippleLayout$3.onAnimationEnd(MaterialRippleLayout.java:336)
       at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:829)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
       at android.view.Choreographer.doCallbacks(Choreographer.java:596)
       at android.view.Choreographer.doFrame(Choreographer.java:556)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:950
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5696)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```69814)
