### ISSUE TITLE
App using Material-ripple crash  when I touch item of recyclerview 

### ISSUE THREAD

**Issue by laiis** [balysv/material-ripple#68]
A Horizontal RecyclerView  crash when I scroll and touch the item of Recyclerview ,

these are crash logs:

07-27 14:26:34.638 3331-3331/x.y.z E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: x.y.z, PID: 3331
                                                                    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@21e6ac58
                                                                        at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
                                                                        at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:844)
                                                                        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:490)
                                                                        at android.widget.ImageView.onDraw(ImageView.java:1037)
                                                                        at android.view.View.draw(View.java:14740)
                                                                        at android.view.View.getDisplayList(View.java:13636)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.View.draw(View.java:14457)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2954)
                                                                        at android.view.View.draw(View.java:14743)
                                                                        at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                        at com.balysv.materialripple.MaterialRippleLayout.draw(MaterialRippleLayout.java:479)
                                                                        at android.view.View.getDisplayList(View.java:13636)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.View.draw(View.java:14457)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2954)
                                                                        at android.view.View.getDisplayList(View.java:13631)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.View.draw(View.java:14457)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
                                                                        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3838)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2954)
                                                                        at android.view.View.draw(View.java:14743)
                                                                        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3308)
                                                                        at android.view.View.getDisplayList(View.java:13636)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
                                                                        at android.view.View.getDisplayList(View.java:13574)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
                                                                        at android.view.View.getDisplayList(View.java:13574)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
                                                                        at android.view.View.getDisplayList(View.java:13574)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
                                                                        at android.view.View.getDisplayList(View.java:13574)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
                                                                        at android.view.View.getDisplayList(View.java:13574)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
                                                                        at android.view.View.getDisplayList(View.java:13574)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
                                                                        at android.view.View.getDisplayList(View.java:13574)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
                                                                        at android.view.View.getDisplayList(View.java:13574)
                                                                        at android.view.View.getDisplayList(View.java:13678)
                                                                        at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
                                                                        at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2401)
                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2273)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1903)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1020)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5762)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                    	at 
07-27 14:26:35.458 3331-3816/x.y.z E/GAv4: Successfully bound to service but never got onServiceConnected callback

**Comment by KomoriWu** [comment]
metoo
